image: ruby:2.5
cache:
 paths:
 - vendor
test:
 script:
 - apt-get update -yqqq
 - apt-get install -y nodejs
 - bundle install --path vendor
 - bundle exec middleman build --verbose
 except:
   - master
pages:
 script:
 - apt-get update -yqqq
 - apt-get install -y nodejs
 - bundle install --path vendor
 - bundle exec middleman build --verbose
 artifacts:
   paths:
   - build
 only:
 - master